is_debug: true 
listen:
  type: port
  port: 9091
  URI_Once: /user/v3
  URI_List: /users/v3
  MitId: 600
storage:
  host: postgres.it-school.top
  port: 6432
  database: comm_db
  username: comm_app
  password: ZHdhZmFlZWFnCg