is_debug: true 
listen:
  type: port
  http_port: 9094
  grpc_port: 9093
  URI_Once: /user/v3/
  URI_List: /users/v3
  HOST: https://reqres.in/api/users
storage:
  host: postgres.it-school.top
  port: 6432
  database: comm_db
  username: comm_app
  password: ZHdhZmFlZWFnCg
User:
  Name: Ivan
  Job: SA
  MinId: 600


